OnlineShop.Web/Models/ManufactureViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineShop.Web.Models
{
    public class ManufactureViewModel
    {
        public Guid ManufactureID { get; set; }

        [Required(ErrorMessage = "Name is REQUIRED")]
        [Display(Name = "Manufacture Name")]
        [StringLength(150, ErrorMessage = "Max length is 150 characters")]
        public string ManufactureName { get; set; }

        [Display(Name = "Logo")]
        [StringLength(256, ErrorMessage = "Max length is 256 characters")]
        public string Logo { get; set; }

        [Display(Name = "Description")]
        [StringLength(750, ErrorMessage = "Max length is 750 characters")]
        public string Description { get; set; }

        [Url]
        [Display(Name = "Link")]
        [StringLength(100, ErrorMessage = "Max length is 100 characters")]
        public string Url { get; set; }
    }
}

OnlineShop.Web/Areas/Admin/Controllers/ManufactureController.cs
using AutoMapper;
using OnlineShop.Common;
using OnlineShop.Data.Models;
using OnlineShop.Service;
using OnlineShop.Web.Controllers;
using OnlineShop.Web.Infrastructure.Core;
using OnlineShop.Web.Infrastructure.Extensions;
using OnlineShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Web.Areas.Admin.Controllers
{
    public class ManufactureController : BaseController
    {
        private IManufactureService _manufactureService;

        public ManufactureController(IManufactureService manufactureService)
        {
            _manufactureService = manufactureService;
        }
        // GET: Admin/Manufacture
        public ActionResult Index(string keyword = null, int page = 1)
        {
            ViewBag.Filter = keyword;
            int pageSize = PaginationHelper.PageSize();
            int totalRow = 0;
            var manufacture = _manufactureService.GetAllPaging(keyword, page, pageSize, out totalRow);
            var model = Mapper.Map<IEnumerable<Manufacture>, IEnumerable<ManufactureViewModel>>(manufacture);

            var pagination = new PaginationSet<ManufactureViewModel>()
            {
                TotalCount = totalRow,
                TotalPages = PaginationHelper.TotalPages(totalRow, pageSize),
                Items = model,
                Page = page,
                MaxPage = PaginationHelper.MaxPage()
            };
            return View(pagination);
        }

        // GET: Admin/Manufacture/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Manufacture/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ManufactureViewModel model)
        {
            try
            {
                var manufacture = new Manufacture();                
                manufacture.UpdateManufacture(model);
                manufacture.ManufactureID = Guid.NewGuid();
                _manufactureService.Add(manufacture);
                _manufactureService.SaveChange();

                SetAlert("AAdded " + model.ManufactureName + " into Manufactures List successfully", "success");

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("create-brand-err", ex.Message);
                return View(model);
            }
        }

        // GET: Admin/Manufacture/Edit/5
        public ActionResult Edit(string id)
        {
            var manufacture = _manufactureService.GetById(new Guid(id));
            var model = Mapper.Map<Manufacture, ManufactureViewModel>(manufacture);
            return View(model);
        }

        // POST: Admin/Manufacture/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, ManufactureViewModel model)
        {
            try
            {
                var manufacture = _manufactureService.GetById(new Guid(id));

                manufacture.UpdateManufacture(model);
                manufacture.ManufactureID = new Guid(id);
                _manufactureService.Update(manufacture);
                _manufactureService.SaveChange();
                SetAlert("Updated " + model.ManufactureName + " successfully", "success");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("edit-brand-err", ex.Message);
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult Delete(string id)
        {
            try
            {
                _manufactureService.Delete(new Guid(id));
                _manufactureService.SaveChange();
                SetAlert("Deleted successfully", "success");
                return Json(new
                {
                    status = true
                });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("delete-brand-err", ex.Message);
                return Json(new
                {
                    status = false
                });
            }
        }
    }
}

OnlineShop.Web/Areas/Admin/Views/Manufacture/Create.cshtml
@model OnlineShop.Web.Models.ManufactureViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Product Manufacture</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <div class="col-md-12">
                    <div class="col-md-8">
                        @using (Html.BeginForm("Create", "Manufacture", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Info</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ManufactureName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ManufactureName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ManufactureName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control", @id = "txtImage" }, @id = "txtImage" })
                                        @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                                        <button class="btn btn-primary" id="btnImage">Tải ảnh</button>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                                        @Html.ActionLink("Cancel", "Index", new { controller = "Manufacture" }, new { @class = "btn btn-default custom" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

@section scripts{
    <script>
        $('#btnImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();

        })
    </script>
}

OnlineShop.Web/Areas/Admin/Views/Manufacture/Edit.cshtml
@model OnlineShop.Web.Models.ManufactureViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Product Manufacture</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <div class="col-md-12">
                    <div class="col-md-8">
                        @using (Html.BeginForm("Edit", "Manufacture", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Info</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ManufactureName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ManufactureName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ManufactureName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                               
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
                                        <button class="btn btn-primary" id="btnImage">Tải ảnh</button>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                                        @Html.ActionLink("Cancel", "Index", new { controller = "Manufacture" }, new { @class = "btn btn-default custom" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

@section scripts{
    <script>
        $('#btnImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();

        })
    </script>
}

OnlineShop.Web/Areas/Admin/Views/Manufacture/Index.cshtml
@model OnlineShop.Web.Infrastructure.Core.PaginationSet<OnlineShop.Web.Models.ManufactureViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Product Manufacture</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                List
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="col-xs-12 form-group">
                    <div class="col-md-12">
                        <div class="col-md-8">
                            @using (Html.BeginForm("Index", "Manufacture", FormMethod.Get))
                            {
                                <div class="form-inline">
                                    <input type="text" id="filter" value="@ViewBag.Filter" name="q" class="form-control " placeholder="Please enter keywords..." />
                                    <input type="submit" class="btn btn-primary" value="Search" />
                                </div>
                            }
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-success pull-right"><i class="fa fa-plus"></i> @Html.ActionLink("Create", "Create", new { controller = "Manufacture" }, new { @class = "btn-add" })</button>
                        </div>
                    </div>

                </div>
                <div class="col-xs-12 form-group">
                    <div class="table-responsive">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Manufacture Name</th>
                                        <th>Description</th>
                                        <th>Website</th>
                                        <th>Logo</th>
                                        <th style="width:15%">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var Manufacture in Model.Items)
                                    {
                                        <tr>
                                            <td><a href="/Admin/Manufacture/Edit/@Manufacture.ManufactureID">@Manufacture.ManufactureName</a></td>
                                            <td>@Manufacture.Description</td>
                                            <td>
                                            <a target="_blank" href="@Manufacture.Url">@Manufacture.Url</a>                                                
                                            </td>
                                            <td><img src="@Manufacture.Logo" alt="Image" width="70" height="70" /></td>
                                            <td>
                                                <a href="/Admin/Manufacture/Edit/@Manufacture.ManufactureID" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                                                <button type="button" data-id="@Manufacture.ManufactureID" class="btn btn-sm btn-danger btnDelete"><i class="fa fa-trash-o"></i></button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            @if (Model.TotalPages > 1)
                            {
                                // Create numeric links
                                var startpage = Math.Max(1, Model.Page - Model.MaxPage / 2);
                                var endpage = Math.Min(Model.TotalPages, Model.Page + Model.MaxPage / 2);

                                <nav class="text-center">
                                    <ul class="pagination">
                                        @if (Model.Page > 1)
                {
                                            <li>
                                                <a href="?page=1" data-toggle="tooltip" title="First" aria-label="First">
                                                    <i class="fa fa-angle-double-left"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="?page=@(Model.Page-1)" data-toggle="tooltip" title="Previous" aria-label="Previous">
                                                    <i class="fa fa-angle-left"></i>
                                                </a>
                                            </li>
                                        }
                                        @for (int i = startpage; i <= endpage; i++)
                {
                    if (Model.Page == i)
                    {
                                                <li class="active"><a href="?page=@i" data-toggle="tooltip" title="Page @i">@i</a></li>
                                            }
                                            else
                                            {
                                                <li><a href="?page=@i" data-toggle="tooltip" title="Page @i">@i</a></li>
                                            }
                                        }
                                        @if (Model.Page < Model.TotalPages)
                {
                                            <li>
                                                <a href="?page=@(Model.Page+1)" data-toggle="tooltip" title="Next" aria-label="Next">
                                                    <i class="fa fa-angle-right"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="?page=@Model.TotalPages" data-toggle="tooltip" title="Last" aria-label="Last">
                                                    <i class="fa fa-angle-double-right"></i>
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                </nav>
                            }
                        </div>
                    </div>
                    <!-- /.table-responsive -->
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
@section scripts{
    <script src="~/Assets/Admin/js/deleteManufacture.js"></script>
}