OnlineShop.Web/Areas/Admin/Controllers/ManageProductsController.cs
using AutoMapper;
using OnlineShop.Common;
using OnlineShop.Data.Models;
using OnlineShop.Service;
using OnlineShop.Web.Controllers;
using OnlineShop.Web.Infrastructure.Core;
using OnlineShop.Web.Infrastructure.Extensions;
using OnlineShop.Web.Infrastructure.Helpers;
using OnlineShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Web.Areas.Admin.Controllers
{
    public class ManageProductsController : BaseController
    {
        private IProductService _productService;
        private IProductCategoryService _productCategoryService;
        private IManufactureService _manufactureService;
        private IProductCategoryService _categoryService;

        public ManageProductsController(IProductService productService,
            IProductCategoryService categoryService, IManufactureService manufactureService,
            IProductCategoryService productCategoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _manufactureService = manufactureService;
            _productCategoryService = productCategoryService;
        }

        // GET: Admin/ManageProducts
        public ActionResult Index(string keyword = null, int page = 1, string manufactureId = null)
        {
            ViewBag.Filter = keyword;
            int pageSize = PaginationHelper.PageSize();
            int totalRow = 0;
            Guid? newManufactureId = (Guid?)null;
            if (!string.IsNullOrEmpty(manufactureId))
            {
                newManufactureId = new Guid(manufactureId);
            }
            var products = _productService.GetIncludeManufacturePaging(keyword, page, newManufactureId, pageSize, out totalRow);
            var model = Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products);

            var pagination = new PaginationSet<ProductViewModel>()
            {
                TotalCount = totalRow,
                TotalPages = PaginationHelper.TotalPages(totalRow, pageSize),
                Items = model,
                Page = page,
                MaxPage = PaginationHelper.MaxPage()
            };
            return View(pagination);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new ProductViewModel();
            PrepareProductCategoriesModel(model);
            SetViewBagManufacture();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = new Product();
                product.UpdateProduct(model);

                product.CreatedBy = User.Identity.Name;
                _productService.Add(product);
                _productService.Save();

                SetAlert("Added " + model.ProductName + " into Products List successfully", "success");
                return RedirectToAction("Index");
            }
            PrepareProductCategoriesModel(model);
            SetViewBagManufacture();
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var product = _productService.GetById(new Guid(id));
            var model = Mapper.Map<Product, ProductViewModel>(product);
            PrepareProductCategoriesModel(model);
            SetViewBagManufacture();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = _productService.GetById(new Guid(id));
                product.UpdateProduct(model, "update");
               
                product.UpdatedBy = User.Identity.Name;
                product.UpdatedDate = DateTime.Now;
                _productService.Update(product);
                _productService.Save();

                SetAlert("Updated " + model.ProductName + " successfully", "success");
                return RedirectToAction("Index");
            }
            PrepareProductCategoriesModel(model);
            SetViewBagManufacture();
            return View(model);
        }

        public JsonResult Delete(string id)
        {
            try
            {
                _productService.Delete(new Guid(id));
                _productService.Save();
                SetAlert("Delete product successfully", "success");
                return Json(new
                {
                    status = true
                });
            }
            catch
            {
                return Json(new
                {
                    status = false
                });
            }
        }

        public void SetViewBagProductCategory(Guid? selectedID = null)
        {
            ViewBag.Categories = new SelectList(_productCategoryService.GetChildByDisplayOrder(), "ID", "Name", selectedID);
        }

        [NonAction]
        protected virtual void PrepareProductCategoriesModel(ProductViewModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");
            if (model.CategoryList == null)
                model.CategoryList = new List<SelectListItem>();
            model.CategoryList.Add(new SelectListItem
            {
                Text = "Please choose a category",
                Value = ""
            });
            var categories = SelectListHelper.GetCategoryList(_productCategoryService);
            foreach (var c in categories)
                model.CategoryList.Add(c);
        }

        public void SetViewBagManufacture(Guid? selectedID = null)
        {
            ViewBag.Manufactures = new SelectList(_manufactureService.GetAll(), "ManufactureID", "ManufactureName", selectedID);
        }

    }
}

OnlineShop.Web/Areas/Admin/Views/ManageProducts/Create.cshtml
@model OnlineShop.Web.Models.ProductViewModel
@using OnlineShop.Common.Extensions
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var manufacture = (SelectList)ViewBag.Manufactures;
    var categories = (SelectList)ViewBag.Categories;
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Products</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <div class="col-md-12">
                    <div class="col-md-8">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <div class="col-md-12">
                                    <h4 class="col-md-6">Product Info</h4>
                                    @Html.ActionLink("Cancel", "Index", "ManageProducts", null, new { @class = "btn btn-danger pull-right col-md-1" })
                                </div>
                                <div class="clearfix"></div>
                                <hr />
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                               
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ProductCategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.MyDropDownListFor(model => model.ProductCategoryID, Model.CategoryList, new { @required = true })
                                        @Html.ValidationMessageFor(model => model.ProductCategoryID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ManufactureID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.ManufactureID, new SelectList(manufacture, "Value", "Text"), "Please choose a manufacture", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ManufactureID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ThumbnailImage, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.ThumbnailImage, new { htmlAttributes = new { @class = "form-control col-md-5", @id = "txtImage" }, @id = "txtImage" })
                                        @Html.ValidationMessageFor(model => model.ThumbnailImage, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-4">
                                        <button class="btn btn-primary clear" id="btnImage">Upload Image</button>
                                    </div>
                                </div>
                                                              
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.OriginalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.OriginalPrice, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.OriginalPrice, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PromotionPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.PromotionPrice, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.PromotionPrice, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Warranty, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Warranty, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.FullDescription, new { @class = "form-control", @id="txtFullDescription" })
                                        @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CalculationUnit, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CalculationUnit, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CalculationUnit, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                
                               
                                <div class="form-group">
                                    @Html.LabelFor(model => model.HotFlag, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.CheckBoxFor(model => model.HotFlag)
                                            @Html.ValidationMessageFor(model => model.HotFlag, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.IsBuy, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.CheckBoxFor(model => model.IsBuy)
                                            @Html.ValidationMessageFor(model => model.IsBuy, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                                        @Html.ActionLink("Cancel", "Index", new { controller = "ManageProducts" }, new { @class = "btn btn-default custom" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->
@section scripts{

    <script>
        $('#btnImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        });

        var editor = CKEDITOR.replace('txtFullDescription', {
            customConfig: '/Assets/Lib/ckeditor/config.js',
        });
    </script>
}

OnlineShop.Web/Areas/Admin/Views/ManageProducts/Edit.cshtml
@model OnlineShop.Web.Models.ProductViewModel
@using OnlineShop.Common.Extensions
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var manufacture = (SelectList)ViewBag.Manufactures;
    var categories = (SelectList)ViewBag.Categories;
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Products</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <div class="col-md-12">
                    <div class="col-md-8">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <div class="col-md-12">
                                    <h4 class="col-md-6">Product Info</h4>
                                    @Html.ActionLink("Cancel", "Index", "ManageProducts", null, new { @class = "btn btn-danger pull-right col-md-1" })
                                </div>
                                <div class="clearfix"></div>
                                <hr />
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ProductCategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.MyDropDownListFor(model => model.ProductCategoryID, Model.CategoryList, new { @required = true })
                                        @Html.ValidationMessageFor(model => model.ProductCategoryID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ManufactureID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.ManufactureID, new SelectList(manufacture, "Value", "Text"), "Please choose a manufacture", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ManufactureID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ThumbnailImage, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.ThumbnailImage, new { htmlAttributes = new { @class = "form-control col-md-5", @id = "txtImage" }, @id = "txtImage" })
                                        @Html.ValidationMessageFor(model => model.ThumbnailImage, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-4">
                                        <button class="btn btn-primary clear" id="btnImage">Upload Image</button>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.OriginalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.OriginalPrice, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.OriginalPrice, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PromotionPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.PromotionPrice, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.PromotionPrice, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Warranty, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Warranty, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.FullDescription, new { @class = "form-control", @id= "txtFullDescription" })
                                        @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CalculationUnit, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CalculationUnit, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CalculationUnit, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.HotFlag, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.CheckBoxFor(model => model.HotFlag)
                                            @Html.ValidationMessageFor(model => model.HotFlag, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.IsBuy, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="checkbox">
                                            @Html.CheckBoxFor(model => model.IsBuy)
                                            @Html.ValidationMessageFor(model => model.IsBuy, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                                        @Html.ActionLink("Cancel", "Index", new { controller = "ManageProducts" }, new { @class = "btn btn-default custom" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

@section scripts{
    <script>
        $('#btnImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();

        });

        var editor = CKEDITOR.replace('txtFullDescription', {
            customConfig: '/Assets/Lib/ckeditor/config.js',
        });
    </script>
}