OnlineShop.Web/Areas/Admin/Controllers/ManageProductCategoryController.cs
using AutoMapper;
using OnlineShop.Common;
using OnlineShop.Data.Models;
using OnlineShop.Service;
using OnlineShop.Web.Controllers;
using OnlineShop.Web.Infrastructure.Core;
using OnlineShop.Web.Infrastructure.Extensions;
using OnlineShop.Web.Infrastructure.Helpers;
using OnlineShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace OnlineShop.Web.Areas.Admin.Controllers
{
    public class ManageProductCategoryController : BaseController
    {
        private IProductCategoryService _productCategoryService;

        public ManageProductCategoryController(IProductCategoryService productCategoryService)
        {
            _productCategoryService = productCategoryService;
        }
        // GET: Admin/ManageProductCategory
        public ActionResult Index(string keyword = null, int page = 1)
        {
            ViewBag.Filter = keyword;
            int pageSize = PaginationHelper.PageSize();
            int totalRow = 0;
            var productCategory = _productCategoryService.GetAllPaging(keyword, page, pageSize, out totalRow);
            var model = Mapper.Map<IEnumerable<ProductCategory>, IEnumerable<ProductCategoryViewModel>>(productCategory);

            var pagination = new PaginationSet<ProductCategoryViewModel>()
            {
                TotalCount = totalRow,
                TotalPages = PaginationHelper.TotalPages(totalRow, pageSize),
                Items = model,
                Page = page,
                MaxPage = PaginationHelper.MaxPage()
            };
            return View(pagination);
        }

        // GET: Admin/ManageProductCategory/Create
        public ActionResult Create()
        {
            var model = new ProductCategoryViewModel();
            SetViewBag();
            return View(model);
        }

        // POST: Admin/ManageProductCategory/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductCategoryViewModel model)
        {
            try
            {
                var productCategory = new ProductCategory();
                productCategory.UpdateProductCategory(model);
                productCategory.ID = Guid.NewGuid();
                productCategory.CreatedBy = User.Identity.Name;

                _productCategoryService.Add(productCategory);
                _productCategoryService.SaveChanges();

                SetAlert("Added " + model.Name + " into Product Categories List succcessfully", "success");

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("create-category-err", ex.Message);
                return View(model);
            }
        }

        // GET: Admin/ManageProductCategory/Edit/5
        public ActionResult Edit(string id)
        {
            var productCategory = _productCategoryService.GetByID(new Guid(id));
            var model = Mapper.Map<ProductCategory, ProductCategoryViewModel>(productCategory);
            SetViewBag();
            return View(model);
        }

        // POST: Admin/ManageProductCategory/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, ProductCategoryViewModel model)
        {
            try
            {
                var productCategory = _productCategoryService.GetByID(new Guid(id));

                productCategory.UpdateProductCategory(model);
                productCategory.UpdatedBy = User.Identity.Name;

                _productCategoryService.Update(productCategory);
                _productCategoryService.SaveChanges();
                SetAlert("Updated " + model.Name + " successfully", "success");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("edit-category-err", ex.Message);
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult Delete(string id)
        {
            try
            {
                _productCategoryService.Delete(new Guid(id));
                _productCategoryService.SaveChanges();
                SetAlert("Delete successfully", "success");
                return Json(new
                {
                    status = true
                });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("delete-category-err", ex.Message);
                return Json(new
                {
                    status = false
                });
            }
        }

        #region Helpers

        [NonAction]
        protected virtual void PrepareProductCategoriesModel(ProductCategoryViewModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");
            if (model.ParentList == null)
                model.ParentList = new List<SelectListItem>();
            model.ParentList.Add(new SelectListItem
            {
                Text = "Chưa chọn danh mục",
                Value = ""
            });
            var categories = SelectListHelper.GetCategoryList(_productCategoryService);
            foreach (var c in categories)
                model.ParentList.Add(c);
        }

        public void SetViewBag(Guid? selectedID = null)
        {
            ViewBag.ParentID = new SelectList(_productCategoryService.GetParentByDisplayOrder(), "ID", "Name", selectedID);
        }

        #endregion Helpers
    }
}

OnlineShop.Web/Areas/Admin/Views/ManageProductCategory/Create.cshtml
@model OnlineShop.Web.Models.ProductCategoryViewModel
@using OnlineShop.Common.Extensions
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Product Category</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <div class="col-md-12">
                    <div class="col-md-8">
                        @using (Html.BeginForm("Create", "ManageProductCategory", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Category Info</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                              
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.ParentID, null, "Choose a category", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.CheckBoxFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                                        @Html.ActionLink("Cancel", "Index", new { controller = "ManageProductCategory" }, new { @class = "btn btn-default custom" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

@section scripts{
    <script>
        $('#btnImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();

        })
    </script>
}

OnlineShop.Web/Areas/Admin/Views/ManageProductCategory/Edit.cshtml
@model OnlineShop.Web.Models.ProductCategoryViewModel
@using OnlineShop.Common.Extensions
@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Product Category</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <div class="col-md-12">
                    <div class="col-md-8">
                        @using (Html.BeginForm("Edit", "ManageProductCategory", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Category Info</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>                                

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.ParentID, null, "Choose a category", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                               
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                @Html.HiddenFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control", @Value = Model.CreatedDate.Value, @type = "datetime" } })
                                @Html.HiddenFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control", @Value = Model.CreatedBy} })
                                   
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.CheckBoxFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                               

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
                                        @Html.ActionLink("Cancel", "Index", new { controller = "ManageProductCategory" }, new { @class = "btn btn-default custom" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->

@section scripts{
    <script>
        $('#btnImage').on('click', function (e) {
            e.preventDefault();
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();

        })
    </script>
}

OnlineShop.Web/Areas/Admin/Views/ManageProductCategory/Index.cshtml
@model OnlineShop.Web.Infrastructure.Core.PaginationSet<OnlineShop.Web.Models.ProductCategoryViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Product Category</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Categories List
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="col-xs-12 form-group">
                    <div class="col-md-12">
                        <div class="col-md-8">
                            @using (Html.BeginForm("Index", "ManageProductCategory", FormMethod.Get))
                            {
                                <div class="form-inline">
                                    <input type="text" id="filter" value="@ViewBag.Filter" name="keyword" class="form-control " placeholder="Please enter keywords..." />
                                    <input type="submit" class="btn btn-primary" value="Search" />
                                </div>
                            }
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-success pull-right"><i class="fa fa-plus"></i> @Html.ActionLink("Thêm mới", "Create", new { controller = "ManageProductCategory" }, new { @class = "btn-add" })</button>
                        </div>
                    </div>

                </div>
                <div class="col-xs-12 form-group">
                    <div class="table-responsive">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Alias</th>
                                        <th>Description</th>
                                        <th>Display Order</th>
                                        <th style="width:15%">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var ProductCategory in Model.Items)
                                    {
                                        <tr>
                                            <td><a href="/Admin/ManageProductCategory/Edit/@ProductCategory.ID">@ProductCategory.Name</a></td>
                                            <td>@ProductCategory.Alias</td>
                                            <td>@ProductCategory.Description</td>
                                            <td>@ProductCategory.DisplayOrder</td>
                                            <td>
                                                <a href="/Admin/ManageProductCategory/Edit/@ProductCategory.ID" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i></a>
                                                <button type="button" data-id="@ProductCategory.ID" class="btn btn-sm btn-danger btnDelete"><i class="fa fa-trash-o"></i></button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            @if (Model.TotalPages > 1)
                            {
                                // Create numeric links
                                var startpage = Math.Max(1, Model.Page - Model.MaxPage / 2);
                                var endpage = Math.Min(Model.TotalPages, Model.Page + Model.MaxPage / 2);

                                <nav class="text-center">
                                    <ul class="pagination">
                                        @if (Model.Page > 1)
                {
                                            <li>
                                                <a href="?page=1" data-toggle="tooltip" title="First" aria-label="First">
                                                    <i class="fa fa-angle-double-left"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="?page=@(Model.Page-1)" data-toggle="tooltip" title="Previous" aria-label="Previous">
                                                    <i class="fa fa-angle-left"></i>
                                                </a>
                                            </li>
                                        }
                                        @for (int i = startpage; i <= endpage; i++)
                {
                    if (Model.Page == i)
                    {
                                                <li class="active"><a href="?page=@i" data-toggle="tooltip" title="Page @i">@i</a></li>
                                            }
                                            else
                                            {
                                                <li><a href="?page=@i" data-toggle="tooltip" title="Page @i">@i</a></li>
                                            }
                                        }
                                        @if (Model.Page < Model.TotalPages)
                {
                                            <li>
                                                <a href="?page=@(Model.Page+1)" data-toggle="tooltip" title="Next" aria-label="Next">
                                                    <i class="fa fa-angle-right"></i>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="?page=@Model.TotalPages" data-toggle="tooltip" title="Last" aria-label="Last">
                                                    <i class="fa fa-angle-double-right"></i>
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                </nav>
                            }
                        </div>
                    </div>
                    <!-- /.table-responsive -->
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
@section scripts{
    <script src="~/Assets/Admin/js/deleteProductCategory.js"></script>
}